/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.banco.gui;

import com.banco.modelos.Banco;         
import com.banco.modelos.CuentaBancaria; 
import com.banco.modelos.Usuario;       
import javax.swing.JOptionPane;         
import java.awt.event.WindowAdapter;    
import java.awt.event.WindowEvent;      
import java.text.DecimalFormat;


public class MenuPrincipalFrame extends javax.swing.JFrame {
    private Usuario usuarioLogeado;
    private CuentaBancaria cuentaDelUsuario;
    private Banco miBanco; 

    
    private DecimalFormat df = new DecimalFormat("#,##0.00");


    /**
     * Creates new form MenuPrincipalFrame
     */
    public MenuPrincipalFrame(Usuario usuario, CuentaBancaria cuenta, Banco banco) {
        initComponents();
        this.usuarioLogeado = usuario;
        this.cuentaDelUsuario = cuenta;
        this.miBanco = banco;
        setLocationRelativeTo(null); 

      
        mostrarInformacionCuenta();

    
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                miBanco.guardarCuentas();
                System.out.println("Cuentas guardadas al cerrar la ventana del menú principal.");
                
            }
        });
    }

    
    private void mostrarInformacionCuenta() {
      
        lblBienvenida.setText("¡Bienvenido, " + usuarioLogeado.getLogin() + "!");
        lblNumCuenta.setText("Número de Cuenta: " + cuentaDelUsuario.getNumeroCuenta());
        
        lblSaldo.setText("Saldo Actual: $" + df.format(cuentaDelUsuario.getSaldo()));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBienvenida = new javax.swing.JLabel();
        lblNumCuenta = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        btnConsignar = new javax.swing.JButton();
        btnRetirar = new javax.swing.JButton();
        btnVerHistorial = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBienvenida.setText("¡Bienvenido, Usuario!");

        lblNumCuenta.setText("Número de Cuenta:");

        lblSaldo.setText("Saldo Actual: $0.00");

        btnConsignar.setText("Consignar");
        btnConsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsignarActionPerformed(evt);
            }
        });

        btnRetirar.setText("Retirar");
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });

        btnVerHistorial.setText("Ver Historial");
        btnVerHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerHistorialActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(lblNumCuenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSaldo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btnConsignar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRetirar)
                                .addGap(44, 44, 44)
                                .addComponent(btnVerHistorial))
                            .addComponent(btnSalir))))
                .addGap(47, 47, 47))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblBienvenida)
                .addGap(168, 168, 168))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblBienvenida)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumCuenta)
                    .addComponent(lblSaldo))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsignar)
                    .addComponent(btnRetirar)
                    .addComponent(btnVerHistorial))
                .addGap(75, 75, 75)
                .addComponent(btnSalir)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsignarActionPerformed
        String montoStr = JOptionPane.showInputDialog(this, "Ingrese el monto a consignar:");

    if (montoStr != null && !montoStr.trim().isEmpty()) { 
        try {
            double monto = Double.parseDouble(montoStr); 

            if (cuentaDelUsuario.consignar(monto)) { 
                JOptionPane.showMessageDialog(this, "Consignación exitosa. Saldo actual: $" + df.format(cuentaDelUsuario.getSaldo()), "Consignación", JOptionPane.INFORMATION_MESSAGE);
                mostrarInformacionCuenta(); 
                miBanco.guardarCuentas(); 
            } else {
                JOptionPane.showMessageDialog(this, "Monto de consignación inválido.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un número válido para el monto.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btnConsignarActionPerformed

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
        String montoStr = JOptionPane.showInputDialog(this, "Ingrese el monto a retirar:");

    if (montoStr != null && !montoStr.trim().isEmpty()) {
        try {
            double monto = Double.parseDouble(montoStr);

            if (cuentaDelUsuario.retirar(monto)) { 
                JOptionPane.showMessageDialog(this, "Retiro exitoso. Saldo actual: $" + df.format(cuentaDelUsuario.getSaldo()), "Retiro", JOptionPane.INFORMATION_MESSAGE);
                mostrarInformacionCuenta(); 
                miBanco.guardarCuentas(); 
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo realizar el retiro. Posibles razones:\n- Monto inválido\n- Saldo insuficiente ($" + df.format(cuentaDelUsuario.getSaldo()) + ")", "Error de Retiro", JOptionPane.WARNING_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un número válido para el monto.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btnRetirarActionPerformed

    private void btnVerHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerHistorialActionPerformed
        StringBuilder historialMensaje = new StringBuilder("Historial de Transacciones:\n\n");
    if (cuentaDelUsuario.getHistorialTransacciones().isEmpty()) {
        historialMensaje.append("No hay transacciones registradas.");
    } else {
        for (String transaccion : cuentaDelUsuario.getHistorialTransacciones()) {
            historialMensaje.append(transaccion).append("\n"); 
        }
    }
   
    JOptionPane.showMessageDialog(this, historialMensaje.toString(), "Historial de Cuenta", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnVerHistorialActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
    miBanco.guardarCuentas();
    System.out.println("Cuentas guardadas antes de salir.");
    JOptionPane.showMessageDialog(this, "Gracias por usar el servicio bancario. ¡Hasta pronto!", "Sesión Cerrada", JOptionPane.INFORMATION_MESSAGE);
    this.dispose(); 
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        
       java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
        }
        }
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsignar;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerHistorial;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblNumCuenta;
    private javax.swing.JLabel lblSaldo;
    // End of variables declaration//GEN-END:variables
}
